### ISSUE TITLE
String Extension

### ISSUE THREAD

**Issue by lfarah** [onmyway133/SwiftHash#3]
I'd also be cool to have a string extension, where I could do something like that:

``` swift
"https://www.google.com".toMD5() // 8FFDEFBDEC956B595D257F0AAEEFD623
```

What are your thoughts? I can make a pull request if you want it

**Comment by onmyway133** [comment]
@lfarah I try to avoid extensions when making library, because it may conflict with others. So I use free functions. The consumer can make an extension if he/she likes 🎉

**Comment by lfarah** [comment]
Sure, no problems 😉
