### ISSUE TITLE
SPM Integration

### ISSUE THREAD

**Issue by lfarah** [onmyway133/SwiftHash#4]
I'd be cool to add [Swift Package Manager](https://github.com/apple/swift-package-manager) integration.

**Comment by onmyway133** [comment]
@lfarah actually I follow the SPM structures, you can see the "Sources" folder. I haven't tried integrated this with SPM, to be honest 😄

**Comment by lfarah** [comment]
@vsouza wanna try it out?

**Comment by vsouza** [comment]
#6 😄

**Comment by onmyway133** [comment]
@lfarah @vsouza many thanks. I see that @dkhamsing has some bots like https://github.com/awesome-bot and https://github.com/dkhamsing/cocoapods-readme

I think we can automate this

**Comment by vsouza** [comment]
@onmyway133 You should have add this new commit on tag, the tag 0.1.0 doesn't have this Package.swift file. So, SPM will not work. You can create a new tag and solve this more easily.

**Comment by onmyway133** [comment]
@vsouza oh right. I just moved the tag. 🎉
