### ISSUE TITLE
not building in carthage

### ISSUE THREAD

**Issue by nboyd-sportdx** [onmyway133/SwiftHash#7]
xcode 8.3
carthage 0.23

Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/lm/vqpb2z590sxb4k5kl98z6_t80000gn/T/carthage-xcodebuild.CqlWjr.log

**Comment by vincenzoraco** [comment]
I've the same issue. Does this package support Swift 3?

**Comment by onmyway133** [comment]
@nboyd-sportdx @vincenzoraco Hi, do you use SwiftHash 1.4.0 https://github.com/onmyway133/SwiftHash/releases ?

**Comment by nboyd-sportdx** [comment]
hello.  i'm using carthage for my ios progject...

**Comment by onmyway133** [comment]
@nboyd-sportdx then you need to specify the version in `Cartfile`

Please try this and let me know if it works
```
github "onmyway133/SwiftHash" "1.4.0"
```

**Comment by vadymmarkov** [comment]
@onmyway133 Doesn't work with Swift 4 version:
```
github "onmyway133/SwiftHash" "2.0.0"
```
