### ISSUE TITLE
MD5 decoding issue

### ISSUE THREAD

**Issue by vnanaware** [onmyway133/SwiftHash#8]
Input: print(MD5("admin123@#").lowercased()) 
Output:  be137a85775380a9ab05ae0d00cca90e

So now I want to decode it How to do it, using MD5 for swift 3?

**Comment by onmyway133** [comment]
@vnanaware You want to decode this hash value back to the original string?

**Comment by vnanaware** [comment]
Yes, How to do this, Please help me.

**Comment by onmyway133** [comment]
@vnanaware Hi, hash is only one way https://crackstation.net/hashing-security.htm, unless you get a quantum machine
